


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import java.io.File;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class ManagerManageOrders extends javax.swing.JFrame {

    /**
     * Creates new form ManagerViewOrders
     */
    // Jayren
    //File viewFeedbackFile = new File("C:\\Users\\hp\\Desktop\\APU\\Year 2\\Modules\\OODJ\\jrenOODJ_Assignment\\src\\oodj_assignment\\Feedback.txt");
    // Hao
     File viewFeedbackFile = new File("C:\\Users\\HAO\\Documents\\NetBeansProjects\\OODJ_Assignment\\src\\oodj_assignment\\Feedback.txt");
    
    
    ViewOrder obj_orders = new ViewOrder();
    String[][] allorders = obj_orders.managerOrderHistory; 
    
    public ManagerManageOrders() {
        initComponents();
        
        //allOrderList
        DefaultListModel temp1 = new DefaultListModel();
        allOrderList.setModel(temp1);
        for(int i = 0; i < allorders.length; i++)
        {
            temp1.addElement(allorders[i][0] + ": " + allorders[i][1]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelOrders1 = new javax.swing.JPanel();
        lblRecentOrders1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableOrders1 = new javax.swing.JTable();
        btnViewOrders1 = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        lblRecentOrders2 = new javax.swing.JLabel();
        apuLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allOrderList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        PanelOrders1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange));

        lblRecentOrders1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRecentOrders1.setText("PENDING ORDERS:");

        TableOrders1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableOrders1);

        btnViewOrders1.setBackground(new java.awt.Color(254, 120, 83));
        btnViewOrders1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        btnViewOrders1.setForeground(new java.awt.Color(242, 242, 242));
        btnViewOrders1.setText("EDIT ORDER");
        btnViewOrders1.setAlignmentY(0.0F);
        btnViewOrders1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnViewOrders1.setBorderPainted(false);
        btnViewOrders1.setIconTextGap(30);
        btnViewOrders1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrders1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOrders1Layout = new javax.swing.GroupLayout(PanelOrders1);
        PanelOrders1.setLayout(PanelOrders1Layout);
        PanelOrders1Layout.setHorizontalGroup(
            PanelOrders1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrders1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRecentOrders1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelOrders1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOrders1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOrders1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnViewOrders1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelOrders1Layout.setVerticalGroup(
            PanelOrders1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrders1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblRecentOrders1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewOrders1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnExit1.setBackground(new java.awt.Color(254, 120, 83));
        btnExit1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(242, 242, 242));
        btnExit1.setText("EXIT");
        btnExit1.setAlignmentY(0.0F);
        btnExit1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnExit1.setBorderPainted(false);
        btnExit1.setIconTextGap(30);
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        lblRecentOrders2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRecentOrders2.setText("COMPLETED ORDERS:");

        apuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/Pictures/apcafelogo.png"))); // NOI18N
        apuLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        allOrderList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "O1     TAN JIN HAO", "O2     TAN JIN HAO", "O3     JAY REN" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(allOrderList);

        jButton1.setText("View Feedback");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ViewPayment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apuLogo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(lblRecentOrders2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit1)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblRecentOrders2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnViewOrders1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrders1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewOrders1ActionPerformed

    private void ViewFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFeedbackActionPerformed
       //JOptionPane.showMessageDialog(null ,"1.User is satisfied with order process\n2.No unnessary steps\n3.User think it is more convenient\n4.Suggestion:nothing","Feedback", JOptionPane.INFORMATION_MESSAGE);
       
       if (allOrderList.isSelectionEmpty())
       {
           JOptionPane.showMessageDialog(null, "Please select an Order!", "Error!", JOptionPane.INFORMATION_MESSAGE);
       }
       else
       {
            //get orderID on its own
            String order = allOrderList.getSelectedValue();
            String[] splitorder = order.split(":");
            String orderid = splitorder[0];

            String satisfy = null;
            String neccessary = null;
            String convenient = null;
            String suggestion = null;
            Boolean hasfeedbackflag = false;

            //check feedback txt for orderid
            try
            {
                 Scanner scan = new Scanner(viewFeedbackFile);
                 scan.useDelimiter("[:\n]");

                //check if orderid equals
                //then only read the next few 

                while (scan.hasNext())
                {
                     if (scan.next().equals(orderid))
                     {
                         hasfeedbackflag = true;
                         satisfy = scan.next();
                         neccessary = scan.next();
                         convenient = scan.next();
                         suggestion = scan.next();

                         JOptionPane.showMessageDialog(null, "1. " + satisfy + "\n2. " + neccessary + "\n3. " + convenient + "\n4. Suggestions: " + suggestion, "Feedback", JOptionPane.INFORMATION_MESSAGE);
                         scan.close();
                     }
                }

                if (hasfeedbackflag == false)
                {
                     JOptionPane.showMessageDialog(null, "No Feedback From User!", "Feedback", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            catch(Exception e)
            {

            }
       }
    }//GEN-LAST:event_ViewFeedbackActionPerformed

    private void ViewPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPaymentActionPerformed
    
    //JOptionPane.showMessageDialog(null ,"1.\n2.\n3.\n4.","Feedback", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    
    //get index of selection from list
    //use existing allorders[i][] list
    //take allorders[i][3], [i][4], [i][5]

       if (allOrderList.isSelectionEmpty())
       {
           JOptionPane.showMessageDialog(null, "Please select an Order!", "Error!", JOptionPane.INFORMATION_MESSAGE);
       }
       else
       {
           int index = allOrderList.getSelectedIndex();
           String order = allorders[index][3];
           String paymentmethod = allorders[index][4];
           String total = allorders[index][5];
           JOptionPane.showMessageDialog(null, "Order: " + order + "\nPayment Method: " + paymentmethod + "\nTotal: RM" + total);
       }
    }//GEN-LAST:event_ViewPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerManageOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelOrders1;
    private javax.swing.JTable TableOrders1;
    private javax.swing.JList<String> allOrderList;
    private javax.swing.JLabel apuLogo;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnViewOrders1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRecentOrders1;
    private javax.swing.JLabel lblRecentOrders2;
    // End of variables declaration//GEN-END:variables
}
