/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author HAO
 */
public class RemoveItem extends javax.swing.JFrame {

    /**
     * Creates new form RemoveItem
     */
    MenuManagement objMM = new MenuManagement();
    public RemoveItem() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLocal = new javax.swing.JRadioButton();
        btnWestern = new javax.swing.JRadioButton();
        btnBeverage = new javax.swing.JRadioButton();
        cbBoxFood = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 120, 83));
        jLabel1.setText("Edit Price");

        btnLocal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLocal.setForeground(new java.awt.Color(254, 120, 83));
        btnLocal.setText("Local Food");
        btnLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalActionPerformed(evt);
            }
        });

        btnWestern.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnWestern.setForeground(new java.awt.Color(254, 120, 83));
        btnWestern.setText("Western Food");
        btnWestern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWesternActionPerformed(evt);
            }
        });

        btnBeverage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBeverage.setForeground(new java.awt.Color(254, 120, 83));
        btnBeverage.setText("Beverage");
        btnBeverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeverageActionPerformed(evt);
            }
        });

        cbBoxFood.setMaximumRowCount(200);
        cbBoxFood.setEnabled(false);
        cbBoxFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoxFoodActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Item to remove :");

        btnRemove.setBackground(new java.awt.Color(255, 51, 51));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnExit1.setBackground(new java.awt.Color(254, 120, 83));
        btnExit1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(242, 242, 242));
        btnExit1.setText("EXIT");
        btnExit1.setAlignmentY(0.0F);
        btnExit1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnExit1.setBorderPainted(false);
        btnExit1.setIconTextGap(30);
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBoxFood, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLocal)
                                .addGap(30, 30, 30)
                                .addComponent(btnWestern)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnBeverage)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLocal)
                    .addComponent(btnWestern)
                    .addComponent(btnBeverage))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbBoxFood, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit1))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalActionPerformed
         
        if (btnLocal.isSelected()) {
            btnWestern.setEnabled(Boolean.FALSE);
            btnBeverage.setEnabled(Boolean.FALSE);
            cbBoxFood.setEnabled(Boolean.TRUE);
            objMM.load_SelectedMenu_TOComboBox("Local", cbBoxFood);
            cbBoxFood.setSelectedIndex(-1);
        }
        else{
            cbBoxFood.setEnabled(Boolean.FALSE);
            btnWestern.setEnabled(Boolean.TRUE);
            btnBeverage.setEnabled(Boolean.TRUE);
            objMM.emptyComboBx(cbBoxFood);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocalActionPerformed

    private void btnWesternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWesternActionPerformed
      cbBoxFood.setSelectedIndex(-1);
        if (btnWestern.isSelected()) {
            btnLocal.setEnabled(Boolean.FALSE);
            btnBeverage.setEnabled(Boolean.FALSE);
            cbBoxFood.setEnabled(Boolean.TRUE);
            
            objMM.load_SelectedMenu_TOComboBox("Western Food", cbBoxFood);
            cbBoxFood.setSelectedIndex(-1);
        }
        else{
           
            cbBoxFood.setEnabled(Boolean.FALSE);
            btnLocal.setEnabled(Boolean.TRUE);
            btnBeverage.setEnabled(Boolean.TRUE);
            objMM.emptyComboBx(cbBoxFood);
        }
    }//GEN-LAST:event_btnWesternActionPerformed

    private void btnBeverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeverageActionPerformed
       cbBoxFood.setSelectedIndex(-1);
        if (btnBeverage.isSelected()) {
            btnLocal.setEnabled(Boolean.FALSE);
            btnWestern.setEnabled(Boolean.FALSE);
            cbBoxFood.setEnabled(Boolean.TRUE);
            objMM.load_SelectedMenu_TOComboBox("Beverage", cbBoxFood);
            cbBoxFood.setSelectedIndex(-1);
        }
        else{
            cbBoxFood.setEnabled(Boolean.FALSE);
            btnLocal.setEnabled(Boolean.TRUE);
            btnWestern.setEnabled(Boolean.TRUE);
            objMM.emptyComboBx(cbBoxFood);
        }
    }//GEN-LAST:event_btnBeverageActionPerformed

    private void cbBoxFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoxFoodActionPerformed
       
    }//GEN-LAST:event_cbBoxFoodActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if (cbBoxFood.getSelectedIndex()!= -1) {

            int reply =JOptionPane.showConfirmDialog(null,"Do u want to remove " + cbBoxFood.getSelectedItem()+" from the menu?","Confirmation",JOptionPane.YES_NO_OPTION);
            if(reply == JOptionPane.YES_OPTION){
                objMM.removeItem_Write_ToMenuFile(cbBoxFood.getSelectedItem().toString());
                JOptionPane.showMessageDialog(null,cbBoxFood.getSelectedItem().toString()+" has been removed sucessfully");
                this.dispose();
                new UpdateMenu().setVisible(true);
            }
        }
        else
        JOptionPane.showMessageDialog(null,"Please ensure item to be removed was selected!","Warning",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UpdateMenu().setVisible(true);
    }//GEN-LAST:event_btnExit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnBeverage;
    private javax.swing.JButton btnExit1;
    private javax.swing.JRadioButton btnLocal;
    private javax.swing.JButton btnRemove;
    private javax.swing.JRadioButton btnWestern;
    private javax.swing.JComboBox<String> cbBoxFood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
