/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import org.xml.sax.Attributes;

/**
 *
 * @author HAO
 */
public class UserPayment extends javax.swing.JFrame {

    /**
     * Creates new form UserPayment
     */
    String grandTotal;
    UserFeedBack objFeedBack =  new UserFeedBack();
    
    public UserPayment() {
        initComponents();
        CardPanel.hide(); 
        onlineBankingPanel.hide();
    }
    
    void set_GrandTotal(String grandTotal){
        this.grandTotal = grandTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jLabel5 = new javax.swing.JLabel();
        cbBxPaymentMethod1 = new javax.swing.JComboBox<>();
        onlineBankingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbBxOnlineBanking = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        textFieldAccNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblGTotalOnline = new javax.swing.JLabel();
        btnOnlineBankingPay = new javax.swing.JButton();
        CardPanel = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        txtCardNum1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCardNum2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCardNum3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCardNum4 = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        txtFldSecurityCode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCardPay = new javax.swing.JButton();
        lblGTotalCard = new javax.swing.JLabel();
        textFieldAccountHolder = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(254, 120, 83));
        jLabel22.setText("Payment");

        label1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label1.setText("Account Holder name :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Payment Method :");

        cbBxPaymentMethod1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online Banking", "Credit Card", "Debit Card", " " }));
        cbBxPaymentMethod1.setSelectedIndex(-1);
        cbBxPaymentMethod1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbBxPaymentMethod1PopupMenuWillBecomeVisible(evt);
            }
        });
        cbBxPaymentMethod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBxPaymentMethod1ActionPerformed(evt);
            }
        });

        onlineBankingPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Online Banking with:");

        cbBxOnlineBanking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maybank2u", "CIMB Clicks", "Public Bank", "RHB Now", "Hong Leong Connect", "Ambank", "MyBSN", "Bank Rakyat", "UOB", "Affin Bank", "Bank Islam", "HSBC Online", " " }));
        cbBxOnlineBanking.setSelectedIndex(-1);
        cbBxOnlineBanking.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbBxOnlineBankingPropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Account No :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Amount to paid : RM");

        lblGTotalOnline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGTotalOnline.setForeground(new java.awt.Color(51, 51, 255));
        lblGTotalOnline.setText("0.00");

        btnOnlineBankingPay.setText("Pay");
        btnOnlineBankingPay.setAlignmentX(0.5F);
        btnOnlineBankingPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineBankingPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout onlineBankingPanelLayout = new javax.swing.GroupLayout(onlineBankingPanel);
        onlineBankingPanel.setLayout(onlineBankingPanelLayout);
        onlineBankingPanelLayout.setHorizontalGroup(
            onlineBankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onlineBankingPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(onlineBankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(onlineBankingPanelLayout.createSequentialGroup()
                        .addGroup(onlineBankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(onlineBankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBxOnlineBanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(onlineBankingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGTotalOnline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOnlineBankingPay)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        onlineBankingPanelLayout.setVerticalGroup(
            onlineBankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onlineBankingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(onlineBankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbBxOnlineBanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(onlineBankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(onlineBankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(onlineBankingPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(onlineBankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblGTotalOnline))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onlineBankingPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btnOnlineBankingPay)
                        .addGap(40, 40, 40))))
        );

        CardPanel.setBackground(new java.awt.Color(204, 204, 204));

        label3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label3.setText("Card Number:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("-");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("-");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("-");

        label2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label2.setText("Security Code:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Amount to paid : RM");

        btnCardPay.setText("Pay");
        btnCardPay.setAlignmentX(0.5F);
        btnCardPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardPayActionPerformed(evt);
            }
        });

        lblGTotalCard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGTotalCard.setForeground(new java.awt.Color(51, 51, 255));
        lblGTotalCard.setText("0.00");

        javax.swing.GroupLayout CardPanelLayout = new javax.swing.GroupLayout(CardPanel);
        CardPanel.setLayout(CardPanelLayout);
        CardPanelLayout.setHorizontalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardPanelLayout.createSequentialGroup()
                        .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CardPanelLayout.createSequentialGroup()
                                .addComponent(txtCardNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCardNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCardNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCardNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CardPanelLayout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(txtFldSecurityCode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(CardPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGTotalCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCardPay)
                        .addGap(26, 26, 26))))
        );
        CardPanelLayout.setVerticalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CardPanelLayout.createSequentialGroup()
                        .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCardNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtCardNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtCardNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtCardNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFldSecurityCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(lblGTotalCard)
                    .addComponent(btnCardPay)))
        );

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldAccountHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbBxPaymentMethod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(onlineBankingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbBxPaymentMethod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAccountHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onlineBankingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCardPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardPayActionPerformed
        int checklist = 3;
        Payment objPayment =  new Payment();
        if (!(objPayment.verifyAccountHolderName(textFieldAccountHolder))){ 
            JOptionPane.showMessageDialog(null,"Please enter valid Account Holder name","Warning" ,JOptionPane.WARNING_MESSAGE);
            checklist--;
        }     
        if ( !(objPayment.verifyCardNo(txtCardNum1) &&objPayment.verifyCardNo(txtCardNum2)&&objPayment.verifyCardNo(txtCardNum3) &&objPayment.verifyCardNo(txtCardNum4))){
            JOptionPane.showMessageDialog(null,"Please enter valid card number.","Warning" ,JOptionPane.WARNING_MESSAGE);
            checklist--;
        }
        if (!(objPayment.verifySecurityCode(txtFldSecurityCode))){
            JOptionPane.showMessageDialog(null,"Please enter valid 3 digit security code.","Warning" ,JOptionPane.WARNING_MESSAGE);
            checklist--;
            }
        if(checklist ==3){JOptionPane.showMessageDialog(null, "Payment done succesfully");
        Order objOrder = new Order();
        objOrder.setPaymentDetails(cbBxPaymentMethod1.getSelectedItem().toString(), grandTotal);
        objOrder.generate_Order_Id();
        objOrder.write_Order_to_OrderFIle();
        int reply = JOptionPane.showConfirmDialog(null,"Are you enjoying the order process? \n Give us some feedback.","Reminder", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.dispose();
            objFeedBack.setVisible(true);
        }
        else{
            this.dispose();
            new UserInterface().setVisible(true);
        }
        }
            
        
        
    }//GEN-LAST:event_btnCardPayActionPerformed

    private void cbBxPaymentMethod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBxPaymentMethod1ActionPerformed
        onlineBankingPanel.show();
        CardPanel.show();
        
        if (cbBxPaymentMethod1.getSelectedIndex()==0) {
            CardPanel.hide();
            onlineBankingPanel.show(); 
            lblGTotalOnline.setText(grandTotal);
        }
        else if (cbBxPaymentMethod1.getSelectedIndex()==1 ||cbBxPaymentMethod1.getSelectedIndex()==2 ) {
            onlineBankingPanel.hide();
            CardPanel.show();
            lblGTotalCard.setText(grandTotal);}  
    }//GEN-LAST:event_cbBxPaymentMethod1ActionPerformed

    private void cbBxPaymentMethod1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbBxPaymentMethod1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBxPaymentMethod1PopupMenuWillBecomeVisible

    private void btnOnlineBankingPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineBankingPayActionPerformed
        Payment objPayment = new Payment();
        int checklist = 3;
        if (!(objPayment.verifyAccountHolderName(textFieldAccountHolder))) {
            JOptionPane.showMessageDialog(null,"Please enter valid Account Holder name","Warning" ,JOptionPane.WARNING_MESSAGE);
            checklist--;
        }
        if (cbBxOnlineBanking.getSelectedIndex()== -1){
            JOptionPane.showMessageDialog(null,"Please select online banking platform.","Warning" ,JOptionPane.WARNING_MESSAGE);
            checklist--;
        }
        if (!objPayment.verifyAccountNo(textFieldAccNo)) {
                JOptionPane.showMessageDialog(null,"Please enter valid Account no","Warning" ,JOptionPane.WARNING_MESSAGE);
                checklist--;
        }
        if(checklist ==3){JOptionPane.showMessageDialog(null, "Payment done succesfully");
        Order objOrder = new Order();
        objOrder.setPaymentDetails(cbBxPaymentMethod1.getSelectedItem().toString(), grandTotal);
        objOrder.generate_Order_Id();
        objOrder.write_Order_to_OrderFIle();
        int reply = JOptionPane.showConfirmDialog(null,"Are you enjoying the order process? \n Give us some feedback.","Reminder", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.hide();
            objFeedBack.setVisible(true);
        }
        else{
            this.hide();
            new UserInterface().setVisible(true);
        }
        }
            
    }//GEN-LAST:event_btnOnlineBankingPayActionPerformed

    private void cbBxOnlineBankingPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbBxOnlineBankingPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBxOnlineBankingPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
        new UserInterface().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardPanel;
    private javax.swing.JButton btnCardPay;
    private javax.swing.JButton btnOnlineBankingPay;
    private javax.swing.JComboBox<String> cbBxOnlineBanking;
    private javax.swing.JComboBox<String> cbBxPaymentMethod1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel lblGTotalCard;
    private javax.swing.JLabel lblGTotalOnline;
    private javax.swing.JPanel onlineBankingPanel;
    private javax.swing.JTextField textFieldAccNo;
    private javax.swing.JTextField textFieldAccountHolder;
    private javax.swing.JTextField txtCardNum1;
    private javax.swing.JTextField txtCardNum2;
    private javax.swing.JTextField txtCardNum3;
    private javax.swing.JTextField txtCardNum4;
    private javax.swing.JTextField txtFldSecurityCode;
    // End of variables declaration//GEN-END:variables
}
