/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

/**
 *
 * @author hp
 */
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form ManagerProfile
     */
    public UserProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMyProfile = new javax.swing.JLabel();
        btnUpdateUserProfile = new javax.swing.JButton();
        PanelRegDetails = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblUserTPNo = new javax.swing.JLabel();
        lblUserContact = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUserTPNo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUserName = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtUserContact = new javax.swing.JTextArea();
        lblUserIC = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtUserIC = new javax.swing.JTextArea();
        lblUserDOB = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtUserDOB = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMyProfile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblMyProfile.setForeground(new java.awt.Color(254, 120, 83));
        lblMyProfile.setText("MY PROFILE");
        lblMyProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMyProfileMousePressed(evt);
            }
        });

        btnUpdateUserProfile.setBackground(new java.awt.Color(254, 120, 83));
        btnUpdateUserProfile.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        btnUpdateUserProfile.setForeground(new java.awt.Color(242, 242, 242));
        btnUpdateUserProfile.setText("UPDATE");
        btnUpdateUserProfile.setAlignmentY(0.0F);
        btnUpdateUserProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnUpdateUserProfile.setBorderPainted(false);
        btnUpdateUserProfile.setIconTextGap(30);

        PanelRegDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserName.setText("                            Name :");

        lblUserTPNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserTPNo.setText("                   TP Number :");

        lblUserContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserContact.setText("                  Contact No. :");

        txtUserTPNo.setColumns(20);
        txtUserTPNo.setRows(5);
        jScrollPane1.setViewportView(txtUserTPNo);

        txtUserName.setColumns(20);
        txtUserName.setRows(5);
        jScrollPane2.setViewportView(txtUserName);

        txtUserContact.setColumns(20);
        txtUserContact.setRows(5);
        jScrollPane3.setViewportView(txtUserContact);

        lblUserIC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserIC.setText("                   I.C Number :");

        txtUserIC.setColumns(20);
        txtUserIC.setRows(5);
        jScrollPane6.setViewportView(txtUserIC);

        lblUserDOB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserDOB.setText("     DOB (dd/mm/yyyy) :");

        txtUserDOB.setColumns(20);
        txtUserDOB.setRows(5);
        jScrollPane7.setViewportView(txtUserDOB);

        javax.swing.GroupLayout PanelRegDetailsLayout = new javax.swing.GroupLayout(PanelRegDetails);
        PanelRegDetails.setLayout(PanelRegDetailsLayout);
        PanelRegDetailsLayout.setHorizontalGroup(
            PanelRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                        .addComponent(lblUserTPNo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                        .addComponent(lblUserContact, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                        .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                        .addComponent(lblUserIC, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                        .addComponent(lblUserDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        PanelRegDetailsLayout.setVerticalGroup(
            PanelRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserTPNo))
                .addGap(19, 19, 19)
                .addGroup(PanelRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblUserName)))
                .addGap(14, 14, 14)
                .addGroup(PanelRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUserIC))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUserDOB))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegDetailsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUserContact))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 609, Short.MAX_VALUE)
                .addComponent(lblMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdateUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanelRegDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMyProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(PanelRegDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMyProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyProfileMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMyProfileMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelRegDetails;
    private javax.swing.JButton btnUpdateUserProfile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblMyProfile;
    private javax.swing.JLabel lblUserContact;
    private javax.swing.JLabel lblUserDOB;
    private javax.swing.JLabel lblUserIC;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserTPNo;
    private javax.swing.JTextArea txtUserContact;
    private javax.swing.JTextArea txtUserDOB;
    private javax.swing.JTextArea txtUserIC;
    private javax.swing.JTextArea txtUserName;
    private javax.swing.JTextArea txtUserTPNo;
    // End of variables declaration//GEN-END:variables
}
